### ISSUE TITLE
Add option to keep clipboard working when re-enabling resistFingerprinting

### ISSUE THREAD

**Issue by whispy** [Aaron-P/ToggleResistFingerprinting#4]
1. Have `privacy.resistFingerprinting` on and `dom.event.clipboardevents.enabled` set to true
2. Toggle `privacy.resistFingerprinting` off
3. Toggle `privacy.resistFingerprinting` back on

**Expected Result**
- `dom.event.clipboardevents.enabled` would be set to `true` (as it was set prior)

**Actual Result**
- `dom.event.clipboardevents.enabled` is set to `false` (due to `privacy.resistFingerprinting` setting it)

Since a similar feature already exists to override the window size, it would be useful if this could be added too.

**Comment by Aaron-P** [comment]
Unless I'm missing it someplace I don't think dom.event.clipboardevents.enabled is settable by a webextension. It's not listed in either the browser.browserSettings or browser.privacy API documentation. That being the case, there's nothing I can really do about it at an extension level, you would need to either request that they add that ability to the webextension API or if you think the value not being reverted is a bug, create a bug report for it on Mozilla's bug tracker.

**Comment by Aaron-P** [comment]
Closing this until something changes in the APIs that lets me fix this.
