### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by Korkycat** [Aaron-P/ToggleResistFingerprinting#6]
As I have said in your add-on comments, I have no toolbar button anywhere in firefox 89.0.2. I also added your addon to to Firefox Nightly 91.0a 1. I can confirm there is toolbar button. I've also checked in customization in both browsers.

**Comment by Aaron-P** [comment]
Okay I have a few questions regarding your 89.0.2 installation:

1. Do you use a custom theme?
2. Have you edited any settings in about:config or userChrome.css/userContent.css?
3. If you go to about:profiles and click on "Create a New Profile", name the new profile something like "Test". Then under profile "Test" click "Launch profile in a new browser" and install the extension in the new profile, does the icon show up? **Note that after you create the new "Test" profile, you will need to click the "Set as default profile" button under your original profile. When you create a new profile it automatically makes the new one the default.**
4. If you go to about:debugging#/runtime/this-firefox and click the "Inspect" button next to the extension, are there any errors in the Console window that opens?

**Comment by Aaron-P** [comment]
The icon should look like one of the images below:

![image](https://user-images.githubusercontent.com/744119/124756499-091e6f80-df1c-11eb-8677-aea7f1b3478a.png)
![image](https://user-images.githubusercontent.com/744119/124756536-15a2c800-df1c-11eb-9537-f27e94e33834.png)

**Comment by Korkycat** [comment]
I use these;
Do you use a custom theme?
Have you edited any settings in about:config or userChrome.css/userContent.css?
However, in nightly which I don't use a lot I put the theme back to a firefox official theme and there is still no toolbar icon.

**Comment by Aaron-P** [comment]
What settings/styles have you changed using either about:config or userChrome.css/userContent.css?

**Comment by Korkycat** [comment]
There are quite a few about:config settings, in user chrome just hiding the the tab toolbar because I use vertical tabs.

**Comment by Aaron-P** [comment]
The userchrome change is likely the issue. The manifest has the icon going into the tab bar by default, and if you're hiding the default tab bar I don't know where, or if, it will show up.  If you temporarily disable the userchrome so that the original tab bar shows, you should be able to move the icon someplace else.

**Comment by Korkycat** [comment]
Will try your suggestion.

**Comment by Korkycat** [comment]
Great your suggestion works, I'll go and update my review. I've never had a problem with the firstpartyisosolate/true setting, but now the BBC iplayer wont work unless the setting is set to off, it took me a few hours to find out what was wrong, even setting the BBC to 'allow' extract canvas data wouldn't work. So your add-on is handy.

**Comment by Aaron-P** [comment]
>  I've never had a problem with the firstpartyisosolate/true setting, but now the BBC iplayer wont work unless the setting is set to off, it took me a few hours to find out what was wrong, even setting the BBC to 'allow' extract canvas data wouldn't work.

Good that you were able to find the icon, but just so you know, this extension is for toggling the privacy.resistFingerprinting setting, not first party isolation. There probably are extensions that toggle first party isolation, but I _think_ you have to restart the browser whenever you turn first party isolation on/off for it to take effect.

**Comment by Korkycat** [comment]
Sorry, I meant 'privacy.resistFingerprinting' lord knows why I put down 'firstpartyisolate'. Duh.

**Comment by Aaron-P** [comment]
Okay, I'll close the issue then. If you have other problems you can create a new issue for them.
